Latest

diff --git a/.config/taskfiles/image/Taskfile.yml b/.config/taskfiles/image/Taskfile.yml
--- a/.config/taskfiles/image/Taskfile.yml
+++ b/.config/taskfiles/image/Taskfile.yml
@@ -37,18 +37,20 @@ tasks:
       - |
         function compressImage() {
           if exiftool "$1" &> /dev/null; then
-            if (exiftool "$1" | grep Comment | grep tinypng-compressed) &> /dev/null; then
-              true log '`'"$1"'` has already been compressed by TinyPNG'
+            if (exiftool "$1" | grep Comment | grep tinypng-compressed) > /dev/null; then
+              .config/log info '`'"$1"'` has already been compressed by TinyPNG'
             else
               if [ -f ~/.tinypng ]; then
                 {{.NPX_HANDLE}}tinypng "$1"
               else
                 {{.NPX_HANDLE}}tinypng -k "{{.TINYPNG_API_KEY}}" "$1"
               fi
-              exiftool -comment="tinypng-compressed" "$1"
+              .config/log "Adding 'tinypng-compressed' as a comment in the EXIF data"
+              exiftool -overwrite_original -comment="tinypng-compressed" "$1"
+              .config/log success "Successfully compressed $1"
             fi
           else
-            true error 'Failed to extract EXIF data from `$1` so the compression is being skipped'
+            .config/log error 'Failed to extract EXIF data from `$1` so the compression is being skipped'
           fi
         }
         compressImage '{{.CLI_ARGS}}'
@@ -58,22 +60,25 @@ tasks:
       - |
         function compressImage() {
           if exiftool "$1" &> /dev/null; then
-            if (exiftool "$1" | grep Comment | grep tinypng-compressed) &> /dev/null; then
-              true log '`'"$1"'` has already been compressed by TinyPNG'
+            if (exiftool "$1" | grep Comment | grep tinypng-compressed) > /dev/null; then
+              .config/log info '`'"$1"'` has already been compressed by TinyPNG'
             else
               if [ -f ~/.tinypng ]; then
                 {{.NPX_HANDLE}}tinypng "$1"
               else
                 {{.NPX_HANDLE}}tinypng -k "{{.TINYPNG_API_KEY}}" "$1"
               fi
-              exiftool -comment="tinypng-compressed" "$1"
+              .config/log "Adding 'tinypng-compressed' as a comment in the EXIF data"
+              exiftool -overwrite_original -comment="tinypng-compressed" "$1"
+              .config/log success "Successfully compressed $1"
             fi
           else
-            true error 'Failed to extract EXIF data from `$1` so the compression is being skipped'
+            .config/log error 'Failed to extract EXIF data from `$1` so the compression is being skipped'
           fi
         }
-        find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.jpg' -o -name '*.png' \) -print0 |
-          xargs -0 -r -n1 compressImage
+        while read PATHH; do
+          compressImage "$PATHH"
+        done < <(find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.jpg' -o -name '*.png' \))
     sources:
       - '**/*.(jpg|png)'
 
@@ -99,16 +104,15 @@ tasks:
       - task: resize:{{if .CLI_ARGS}}cli{{else}}default{{end}}
 
   resize:cli:
-    env:
-      ARGS_ARRAY:
-        sh: ({{.CLI_ARGS}})
     cmds:
       - |
-        if ! exiftool "${ARGS_ARRAY[3]}" | grep "Image Size" | grep "${ARGS_ARRAY[1]}x${ARGS_ARRAY[2]}; then
-          {{.NPX_HANDLE}}sharp -i "${ARGS_ARRAY[3]}" -o "${ARGS_ARRAY[3]}.resized" resize "${ARGS_ARRAY[1]}" "${ARGS_ARRAY[2]}"
-          mv "${ARGS_ARRAY[3]}.resized" "${ARGS_ARRAY[3]}"
+        ARGS_ARRAY=({{.CLI_ARGS}})
+        if ! exiftool "${ARGS_ARRAY[2]}" | grep "Image Size" | grep "${ARGS_ARRAY[0]}x${ARGS_ARRAY[1]}"; then
+          {{.NPX_HANDLE}}sharp -i "${ARGS_ARRAY[2]}" -o "${ARGS_ARRAY[2]}.resized" resize "${ARGS_ARRAY[0]}" "${ARGS_ARRAY[1]}"
+          mv "${ARGS_ARRAY[2]}.resized" "${ARGS_ARRAY[2]}"
+          .config/log success "Successfully resized ${ARGS_ARRAY[2]}"
         fi
     status:
-      - 'exiftool "${ARGS_ARRAY[3]}" | grep "Image Size" | grep "${ARGS_ARRAY[1]}x${ARGS_ARRAY[2]}'
+      - 'exiftool "${ARGS_ARRAY[2]}" | grep "Image Size" | grep "${ARGS_ARRAY[0]}x${ARGS_ARRAY[1]}"'
 
-  resize:default: true info "Interactive dialog coming eventually.."
+  resize:default: .config/log info "Interactive dialog coming eventually.."
diff --git a/.config/taskfiles/install/Taskfile-software.yml b/.config/taskfiles/install/Taskfile-software.yml
--- a/.config/taskfiles/install/Taskfile-software.yml
+++ b/.config/taskfiles/install/Taskfile-software.yml
@@ -1,38 +1,62 @@
+# eslint-disable eslint-comments/disable-enable-pair, max-lines
 ---
 version: '3'
 
 tasks:
+  act:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: act
+
+  allure:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: allure
+
   brew:
     deps:
       - common
     run: once
     cmds:
       - task: brew:{{OS}}
-    status:
-      - type brew &> /dev/null || [[ "${container:=}" == "docker" ]]
 
+    log:
+      error: Failed to install or load Homebrew
+      start: Ensuring Homebrew is installed and available
+      success: Successfully ensured Homebrew is installed
   brew:cask:
     deps:
       - brew
     run: when_changed
     cmds:
       - brew install --cask {{.CASK}}
+    log:
+      error: Failed to install `{{.CASK}}`
+      start: Ensuring the `{{.CASK}}` Homebrew cask is installed
+      success: Successfully installed `{{.CASK}}`
     status:
-      - type {{.CASK}} &> /dev/null || [[ "${container:=}" == "docker" ]]
+      - type {{.CASK}} &> /dev/null
 
   brew:darwin:
     cmds:
       - |
-        if [ -f "~/.local/homebrew/bin/brew" ] && ! type brew &> /dev/null; then
-          eval "$(~/.local/homebrew/bin/brew shellenv)"
-        elif ! type brew &> /dev/null; then
-          rm -rf ~/.local/homebrew
-          mkdir -p ~/.local/homebrew
-          git clone https://github.com/Homebrew/brew ~/.local/homebrew
-          eval "$(~/.local/homebrew/bin/brew shellenv)"
-          brew update --force --quiet
-          chmod -R go-w "$(brew --prefix)/share/zsh"
+        if ! type brew &> /dev/null; then
+          if sudo -n bash; then
+            echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          else
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          fi
+          if [ '{{.BODEGA}}' != 'true' ]; then
+            task install:software:exit:notice:reload
+          fi
         fi
+      - task: brew:utils
+    status:
+      - type brew &> /dev/null
 
   brew:formulae:
     deps:
@@ -40,60 +64,90 @@ tasks:
     run: when_changed
     cmds:
       - brew install {{.FORMULAE}}
+    log:
+      error: Failed to install `{{.FORMULAE}}`
+      start: Ensuring the `{{.FORMULAE}}` Homebrew formulae is installed
+      success: Successfully installed `{{.FORMULAE}}`
     status:
-      - type {{.FORMULAE}} &> /dev/null || [[ "${container:=}" == "docker" ]]
+      - type {{.FORMULAE}} &> /dev/null
 
   brew:linux:
     run: once
     cmds:
       - |
         function ensureSource() {
-          if ! (cat "$1" | grep "/bin/brew shellenv" &> /dev/null); then
-            echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> "$1"
+          if ! (grep "/bin/brew shellenv" < "$1" &> /dev/null); then
+            echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> "$1"
           fi
         }
-        case "${SHELL}" in
-          */bash*)
-            if [[ -r "${HOME}/.bash_profile" ]]; then
-              SHELL_PROFILE="${HOME}/.bash_profile"
-            else
-              SHELL_PROFILE="${HOME}/.profile"
-            fi
-            ;;
-          */zsh*)
-            SHELL_PROFILE="${HOME}/.zprofile"
-            ;;
-          *)
-            SHELL_PROFILE="${HOME}/.profile"
-            ;;
-        esac
-        if [ -f "~/.local/homebrew/bin/brew" ] && ! type brew &> /dev/null; then
-          eval "$(~/.local/homebrew/bin/brew shellenv)"
-          ensureSource "$SHELL_PROFILE"
-        elif ! type brew &> /dev/null; then
-          rm -rf ~/.local/homebrew
-          mkdir -p ~/.local/homebrew
-          git clone https://github.com/Homebrew/brew ~/.local/homebrew
-          eval "$(~/.local/homebrew/bin/brew shellenv)"
-          brew update --force --quiet
-          ensureSource "$SHELL_PROFILE"
+        if ! type brew &> /dev/null; then
+          if sudo -n bash; then
+            echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          else
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+          fi
+          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
+          ensureSource "$HOME/.profile"
+          if [ '{{.BODEGA}}' != 'true' ]; then
+            task install:software:exit:notice:reload
+          fi
         fi
+    status:
+      - type brew &> /dev/null || [[ "$OPTIMIZED_IMAGE" == 'true' ]]
+
+  brew:utils:
+    run: once
+    cmds:
+      - task: compatibility:coreutils
+      - task: compatibility:findutils
+      - task: compatibility:gnu-sed
+      - task: compatibility:grep
+      - task: compatibility:gnu-tar
+      - task: compatibility:gawk
+    log:
+      error: Failed to setup GNU-compatibility tools
+      start: Installing GNU-compatibility tools for macOS via Homebrew
+      success: Successfully installed GNU-compatibility tools
+    status:
+      - '[ "{{OS}}" != "darwin" ]'
 
   brew:windows:
     cmds:
       - task: common:windows
+
+  codeclimate:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: codeclimate/formulae/codeclimate
+    status:
+      - type codeclimate > /dev/null
 
   common:
     run: once
     cmds:
       - task: common:{{OS}}
 
+    log:
+      error: There was an error ensuring common system tools are present
+      start: Ensuring common system tools are present
+      success: Ensured common system tools are present
   common:darwin:
-    interactive: true
     cmds:
-      - xcode-select --install
+      - task: common:darwin:xcode
+
+  common:darwin:xcode:
+    vars:
+      CLT_STATUS:
+        sh: brew config | grep CLT
+    cmds:
+      - sudo xcode-select --install
+    log:
+      error: Failed to run `sudo xcode-select --install`
+      start: Running `sudo xcode-select --install` to install macOS developer tools
+      success: Successfully ran `sudo xcode-select --install`
     status:
-      - xcode-select -p 2&>1 /dev/null
+      - '[ "{{.CLT_STATUS}}" != "CLT: N/A" ]'
 
   common:linux:
     vars:
@@ -110,61 +164,127 @@ tasks:
           fi
     cmds:
       - task: common:linux:{{.LINUX_FAMILY}}
+    status:
+      - '[[ "$OPTIMIZED_IMAGE" == "true" ]]'
 
   common:linux:archlinux:
     interactive: true
     cmds:
-      - true warn "Archlinux support for Homebrew is not very well documented.. if this does not work and you can get it working, please open a PR :)"
+      - .config/log warn "Archlinux support for Homebrew is not very well documented.. if this does not work and you can get it working, please open a PR :)"
       - |
         sudo pacman update
         sudo pacman -S base-devel curl file git procps-ng
     status:
-      - type curl &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - type git &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - ldconfig -p | grep base-devel || [[ "${container:=}" == "docker" ]]
-      - ldconfig -p | grep file || [[ "${container:=}" == "docker" ]]
-      - ldconfig -p | grep procps-ng || [[ "${container:=}" == "docker" ]]
+      - type curl &> /dev/null
+      - type git &> /dev/null
+      - ldconfig -p | grep base-devel
+      - ldconfig -p | grep file
+      - ldconfig -p | grep procps-ng
 
   common:linux:debian:
     interactive: true
     cmds:
       - |
-        sudo apt-get update
-        sudo apt-get install build-essential curl file git procps
+        .config/log info 'Attempting to install Homebrew dependencies (sudo password required)'
+        sudo apt-get -y update
+        sudo apt-get install -y build-essential curl file git procps
     status:
-      - type curl &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - type git &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - dpkg-query -l build-essential &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - dpkg-query -l file &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - dpkg-query -l procps &> /dev/null || [[ "${container:=}" == "docker" ]]
+      - type curl &> /dev/null
+      - type git &> /dev/null
+      - dpkg-query -l build-essential &> /dev/null
+      - dpkg-query -l file &> /dev/null
+      - dpkg-query -l procps &> /dev/null
 
   common:linux:redhat:
     interactive: true
     cmds:
+      - mkdir -p "$HOME/.config/bodega"
       - |
-        sudo yum groupinstall 'Development Tools'
-        sudo yum install curl file git procps-ng
+        if [ ! -f "$HOME/.config/bodega/yum-devtools-check-ran" ]; then
+          yum grouplist 'Development Tools' &> "$HOME/.config/bodega/yum-devtools-check-ran"
+          DEV_TOOLS_NOT_INSTALLED="$(grep 'No groups match' < "$HOME/.config/bodega/yum-devtools-check-ran" > /dev/null)"
+          if [[ "$DEV_TOOLS_NOT_INSTALLED" == '0' ]]; then
+            sudo yum groupinstall -y 'Development Tools'
+          fi
+          touch "$HOME/.config/bodega/yum-devtools-check-ran"
+        fi
+        if ! rpm --quiet --query curl file git procps-ng; then
+          .config/log info 'Attempting to install Homebrew dependencies (sudo password required)'
+          sudo yum install -y curl file git procps-ng
+        fi
         if [ -f '/etc/os-release' ]; then
           source /etc/os-release
-          if [ "$ID" == 'fedora' ] && [ "$VERSION_ID" -gt "29" ]; then
-            sudo yum install libxcrypt-compat
+          if [[ "$ID" == 'fedora' ]] && [ "$VERSION_ID" -gt "29" ]; then
+            if ! rpm --quiet --query libxcrypt-compat; then
+              .config/log info 'Attempting to install Fedora-specific Homebrew dependency (sudo password required)'
+              sudo yum -y install libxcrypt-compat
+            fi
           fi
         fi
-    status:
-      - type curl &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - type git &> /dev/null || [[ "${container:=}" == "docker" ]]
-      - ldconfig -p | grep file || [[ "${container:=}" == "docker" ]]
-      - ldconfig -p | grep procps-ng || [[ "${container:=}" == "docker" ]]
 
   common:linux:unknown:
     cmds:
-      - true warn 'You are using an operating system that we do not directly support. Please make sure
+      - .config/log warn 'You are using an operating system that we do not directly support. Please make sure
         the equivalent of `build-essential`, `curl`, `file`, `git`, and `procps` are installed.'
 
   common:windows:
     cmds:
-      - true error "Windows is not supported. Try using a Windows WSL environment."
       - exit 1
+
+    log:
+      error: Windows is not supported. Try using a Windows WSL environment.
+  compatibility:findutils:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: findutils
+    status:
+      - type gfind > /dev/null
+
+  compatibility:gawk:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: gawk
+
+  compatibility:gnu-sed:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: gnu-sed
+    status:
+      - type gsed > /dev/null
+
+  compatibility:gnu-tar:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: gnu-tar
+    status:
+      - type gtar > /dev/null
+
+  compatibility:grep:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: grep
+    status:
+      - type ggrep > /dev/null
+
+  container-structure-test:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: container-structure-test
+
+  coreutils:
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: coreutils
+    status:
+      - type gcp > /dev/null || [ "{{OS}}" != "darwin" ]
 
   docker:
     run: once
@@ -177,6 +297,9 @@ tasks:
       - task: brew:cask
         vars:
           CASK: docker
+      - task: exit:notice:restart
+    status:
+      - type docker > /dev/null
 
   docker:linux:
     run: once
@@ -184,6 +307,9 @@ tasks:
       - task: brew:formulae
         vars:
           FORMULAE: docker
+      - task: exit:notice:restart
+    status:
+      - type docker > /dev/null
 
   docker:windows:
     cmds:
@@ -195,6 +321,8 @@ tasks:
       - task: brew:formulae
         vars:
           FORMULAE: goodwithtech/r/dockle
+    status:
+      - type dockle > /dev/null
 
   exiftool:
     run: once
@@ -202,6 +330,41 @@ tasks:
       - task: brew:formulae
         vars:
           FORMULAE: exiftool
+
+  exit:notice:reload:
+    cmds:
+      - .config/log warn 'Software was installed that requires a terminal session reload'
+      - .config/log info 'Please close and re-open the terminal. Then, re-run the same command to continue.'
+      - exit 1
+
+  exit:notice:restart:
+    cmds:
+      - .config/log warn 'Software was installed that requires a system reboot'
+      - .config/log info 'Please reboot the system and re-run the same command after rebooting'
+      - exit 1
+
+  gcloud:
+    run: once
+    cmds:
+      - task: gcloud:{{OS}}
+    status:
+      - type gcloud > /dev/null
+
+  gcloud:darwin:
+    cmds:
+      - task: brew:cask
+        vars:
+          CASK: google-cloud-sdk
+
+  gcloud:linux:
+    cmds:
+      - task: :install:install-doctor
+        vars:
+          SOFTWARE: googlecloudsdk
+
+  gcloud:windows:
+    cmds:
+      - task: common:windows
 
   gh:
     run: once
@@ -236,6 +399,15 @@ tasks:
         vars:
           FORMULAE: go
 
+  grype:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: anchore/grype/grype
+    status:
+      - type grype > /dev/null
+
   jq:
     run: once
     cmds:
@@ -250,20 +422,94 @@ tasks:
         vars:
           FORMULAE: node
 
+  pipx:
+    run: once
+    cmds:
+      - task: pipx:{{OS}}
+    log:
+      error: Failed to ensure `pipx` is installed
+      start: Ensuring `pipx` is installed
+      success: Successfully ensured `pipx` is installed
+    status:
+      - type pipx > /dev/null
+
+  pipx:darwin:
+    deps:
+      - brew
+    cmds:
+      - brew install pipx
+      - pipx ensurepath
+
+  pipx:linux:
+    deps:
+      - :install:software:python
+    cmds:
+      - python3 -m pip install --user pipx
+      - python3 -m pipx ensurepath
+
+  pipx:windows:
+    cmds:
+      - exit 1
+
+    log:
+      error: These scripts are not currently compatible with Windows. Try using WSL.
   poetry:
+    run: once
+    cmds:
+      - task: poetry:{{OS}}
+      - task: exit:notice:reload
+    status:
+      - type poetry > /dev/null
+
+  poetry:darwin:
     run: once
     cmds:
       - task: brew:formulae
         vars:
           FORMULAE: poetry
 
-  python:
+  poetry:linux:
     run: once
     cmds:
       - task: brew:formulae
         vars:
-          FORMULAE: python
+          FORMULAE: poetry
 
+  poetry:windows:
+    cmds:
+      - exit 1
+
+    log:
+      error: These scripts are not currently compatible with Windows. Try using WSL.
+  python:
+    deps:
+      - brew # bug fix
+    run: once
+    cmds:
+      - task: python:{{OS}}
+
+  python:darwin:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: python@3.10
+    status:
+      - type python3 > /dev/null
+
+  python:linux:
+    run: once
+    cmds:
+      - task: :install:install-doctor
+        vars:
+          SOFTWARE: python
+
+  python:windows:
+    cmds:
+      - exit 1
+
+    log:
+      error: These scripts are not currently compatible with Windows. Try using WSL.
   rsync:
     run: once
     cmds:
@@ -277,6 +523,17 @@ tasks:
       - task: brew:formulae
         vars:
           FORMULAE: hudochenkov/sshpass/sshpass
+    status:
+      - type sshpass > /dev/null
+
+  subrepo:
+    run: once
+    cmds:
+      - task: brew:formulae
+        vars:
+          FORMULAE: git-subrepo
+    status:
+      - git subrepo --version > /dev/null || [[ "${container:=}" == "docker" ]]
 
   tokei:
     run: once
@@ -291,6 +548,8 @@ tasks:
       - task: brew:formulae
         vars:
           FORMULAE: aquasecurity/trivy/trivy
+    status:
+      - type trivy > /dev/null
 
   vagrant:
     cmds:
@@ -313,6 +572,9 @@ tasks:
   virtualbox:
     cmds:
       - task: virtualbox:{{OS}}
+      - task: exit:notice:restart
+    status:
+      - type vboxmanage > /dev/null
 
   virtualbox:darwin:
     run: once
@@ -331,6 +593,9 @@ tasks:
   vmware:
     cmds:
       - task: vmware:{{OS}}
+      - task: exit:notice:restart
+    status:
+      - type vmware > /dev/null
 
   vmware:darwin:
     run: once
diff --git a/.config/taskfiles/lint/Taskfile.yml b/.config/taskfiles/lint/Taskfile.yml
--- a/.config/taskfiles/lint/Taskfile.yml
+++ b/.config/taskfiles/lint/Taskfile.yml
@@ -3,22 +3,21 @@ version: '3'
 
 vars:
   ANSIBLE_LINT_CONFIG: .config/ansible-lint.yml
-  COMMITLINT_CONFIG: .config/commitlint.config.cjs
-  CSPELL_CONFIG: .config/.cspell.json
+  CSPELL_CONFIG: .config/cspell.json
   FLAKE8_CONFIG: .config/flake8.toml
   PRETTIERIGNORE_CONFIG: .config/prettierignore
+  SHELLCHECK_EXCLUDE: SC1091
   YAMLLINT_CONFIG: .config/yamllint.yml
 
 tasks:
   all:
     deps:
       - '{{.REPOSITORY_TYPE}}'
-      - prettier
+      - eslint
       - :lint:markdown:markdown
       - :lint:prose:prose
       - shellcheck
       - yaml
-    desc: Lint with all available linters
 
   ansible:
     deps:
@@ -38,7 +37,26 @@ tasks:
 
       For more information, see [Ansible Lint's GitHub page](https://github.com/ansible-community/ansible-lint).
     cmds:
-      - poetry run ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+      - |
+        .config/log info 'Linting the project with ansible-lint'
+        {{.PYTHON_HANDLE}}ansible-lint -c {{.ANSIBLE_LINT_CONFIG}}
+
+  any:
+    deps:
+      - :install:python:requirements
+    desc: Generic linting of files for things like destroyed-symlinks, merge conflicts, etc.
+    cmds:
+      - '{{.PYTHON_HANDLE}}blocklint --wordlist blacklist,slave,whitelist {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-merge-conflict {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-added-large-files {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}check-symlinks {{.CLI_ARGS}}'
+      - '{{.PYTHON_HANDLE}}destroyed-symlinks {{.CLI_ARGS}}'
+
+  codeclimate:
+    deps:
+      - :install:software:codeclimate
+    cmds:
+      - codeclimate
 
   commit:
     deps:
@@ -53,7 +71,16 @@ tasks:
       **Example:**
       `task lint:commit -- 'My commit message'`
     cmds:
-      - if [ ! -z '{{.CLI_ARGS}}' ]; then commitlint -e '{{.CLI_ARGS}}' --config {{.COMMITLINT_CONFIG}}; fi
+      - |
+        if [ ! -z '{{.CLI_ARGS}}' ] && [ '{{.CLI_ARGS}}' != '.git/MERGE_MSG' ] && [ "$(head -c12 < .git/MERGE_MSG)" != 'Merge branch' ]; then
+          cp '{{.CLI_ARGS}}' '{{.CLI_ARGS}}.bak'
+          TMP="$(mktemp)"
+          COMMIT_MSG_NOEMOJI="$(sed 's/^..//' < '{{.CLI_ARGS}}' | xargs)"
+          .config/log info 'Linting commit message (with emoji stripped)'
+          echo "$COMMIT_MSG_NOEMOJI" | {{.NPX_PACKAGE}} commitlint || (mv '{{.CLI_ARGS}}.bak' '{{.CLI_ARGS}}' && exit 1)
+        elif [ '{{.CLI_ARGS}}' == '.git/MERGE_MSG' ]; then
+          .config/log info 'Bypassing commitlint since the message is a merge message'
+        fi
     status:
       - '[[ -z "{{.CLI_ARGS}}" ]]'
     preconditions:
@@ -67,7 +94,7 @@ tasks:
     summary: |
       # Lint Dockerfiles using Hadolint
 
-      Hadolint is a linter for Dockerfiles. This task uses Hadolint to reportrue warnings
+      Hadolint is a linter for Dockerfiles. This task uses Hadolint to report warnings
       and suggestions so that the project is using best practices and is less likely to
       have errors. The task uses Docker to run an ultra-compact container that includes
       Hadolint. Installing Hadolint is done at runtime. The task scans for all files that
@@ -93,6 +120,7 @@ tasks:
       For more information, see [Hadolint's GitHub page](https://github.com/hadolint/hadolint).
     cmds:
       - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}all Dockerfiles{{end}} with a Hadolint Docker image'
         {{if .CLI_ARGS}}
           docker run -v "$PWD:/work" -w /work megabytelabs/hadolint:slim {{.CLI_ARGS}}
         {{else}}
@@ -100,6 +128,10 @@ tasks:
             -name Dockerfile.j2 \) -print0 | xargs -0 -r -n1 docker run -v "$PWD:/work" -w /work \
             megabytelabs/hadolint:slim
         {{end}}
+
+  dockerfile:
+    cmds:
+      - task: docker
 
   eslint:
     deps:
@@ -122,14 +154,45 @@ tasks:
       **Example linting specific pattern of files:**
       `task lint:eslint -- '**/*.js'`
     cmds:
-      - '{{.NPX_HANDLE}}eslint --format pretty {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - >
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format {{.ESLINT_FORMATTER}} --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
+    log:
+      start: Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with ESLint
+      success: Successfully passed the ESLint test (please still address warnings)
+  eslint:warn-all:
+    deps:
+      - :install:modules:local
+      - :install:npm:eslint
+    desc: Convert ESLint errors into warnings in `package.json`
+    summary: |
+      # Convert ESLint Errors into Warnings
+
+      This task will run ESLint against the project and then automatically inline
+      all reported errors as warnings in `package.json`.
+    cmds:
+      - >
+        TMP="$(mktemp)"
+
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format summary --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}} |
+        tee "$TMP"
+
+    log:
+      error: Encountered error while converting `eslint` errors to warnings
+      start: Overriding all errors reported from `eslint` as `warnings` in `package.json`
+      success: Successfully overrode `eslint` errors as warnings
   js:
     deps:
       - :install:modules:local
       - :install:npm:eslint
     cmds:
-      - '{{.NPX_HANDLE}}eslint --format pretty --ext .js,.jsx,.ts {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - >
+        .config/log info 'Linting {{if .CLI_ARGS}}`{{.CLI_ARGS}}`{{else}}JavaScript/TypeScript files{{end}} with ESLint'
+
+        {{.NPX_HANDLE}}eslint -c package.json --no-eslintrc --format pretty --ext .js,.jsx,.ts,.tsx --cache
+        --cache-location .cache/eslintcache {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   lint-staged:
     deps:
@@ -137,7 +200,9 @@ tasks:
       - :install:modules:local
       - :install:python:requirements
     cmds:
-      - '{{.NPX_HANDLE}}lint-staged'
+      - |
+        .config/log info 'Linting changed files'
+        {{.NPX_HANDLE}}lint-staged
 
   packer:
     deps:
@@ -160,9 +225,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
+          .config/log info 'Validating the {{.CLI_ARGS}} Packer template'
           packer validate {{.CLI_ARGS}}
         {{else}}
           for TEMPLATE in *template.json; do
+            .config/log info "Validating the $TEMPLATE Packer template"
             packer validate "$TEMPLATE"
           done
         {{end}}
@@ -185,7 +252,9 @@ tasks:
 
       For more information, see [Prettier's website](https://prettier.io/).
     cmds:
-      - '{{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}'
+      - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with Prettier'
+        {{.NPX_HANDLE}}prettier --ignore-path {{.PRETTIERIGNORE_CONFIG}} --list-different {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   python:
     deps:
@@ -217,9 +286,11 @@ tasks:
     cmds:
       - |
         {{if .CLI_ARGS}}
-          poetry run flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
+          .config/log info 'Linting {{.CLI_ARGS}} with flake8'
+          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} {{.CLI_ARGS}}
         {{else}}
-          poetry run flake8 --config {{.FLAKE8_CONFIG}} .
+          .config/log info 'Linting the project with flake8'
+          {{.PYTHON_HANDLE}}flake8 --config {{.FLAKE8_CONFIG}} .
         {{end}}
 
   shell:
@@ -251,10 +322,12 @@ tasks:
       For more information, see [Shellcheck's GitHub page](https://github.com/koalaman/shellcheck).
     cmds:
       - |
+        .config/log info 'Linting with Shellcheck'
         {{if .CLI_ARGS}}
-          {{.NPX_HANDLE}}shellcheck {{.CLI_ARGS}}
+          {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}} {{.CLI_ARGS}}
         {{else}}
-          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck
+          find . -type d \( {{.IGNORE_FOLDERS}} \) -prune -o -type f \( -name '*.sh' -o -name '*.sh.j2' \) \
+          -print0 | xargs -0 -r -n1 {{.NPX_HANDLE}}shellcheck -e {{.SHELLCHECK_EXCLUDE}}
         {{end}}
 
   spelling:
@@ -264,7 +337,7 @@ tasks:
     summary: |
       # Check for spelling errors in staged files
 
-      Use cspell to check for possible spelling errors using the configuration stored in `.common/.cspell.json`.
+      Use cspell to check for possible spelling errors using the configuration stored in `.config/cspell.json`.
 
       This task is utilized by the pre-commit hook. For more information about cspell, see the
       [cspell NPM page](https://www.npmjs.com/package/cspell).
@@ -283,19 +356,32 @@ tasks:
 
   spelling:cli:
     cmds:
-      - cmd: '{{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}}'
+      - cmd: |
+          set -e
+          EXIT_CODE=0
+          .config/log info 'Running a spell-check with `cspell`'
+          {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} {{.CLI_ARGS}} || EXIT_CODE=$?
+          if [ "$EXIT_CODE" != '0' ]; then
+            .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+          fi
         ignore_errors: true
 
   spelling:staged:
     deps:
       - :install:npm:cspell
       - :install:software:git
-    env:
-      STAGED_FILES: git diff --cached --name-only
     cmds:
       - cmd: |
-          if [ '{{.STAGED_FILES}}' ]; then
-            {{.NPX_HANDLE}}cspell --no-summary --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} "$STAGED_FILES"
+          STAGED_FILES="$(git diff --cached --name-only)"
+          if [ -n "$STAGED_FILES" ]; then
+            set -e
+            EXIT_CODE=0
+            .config/log info 'Running a spell-check on staged files with `cspell`'
+            # Must not quote $STAGED_FILES
+            {{.NPX_HANDLE}}cspell --no-progress --show-context --no-must-find-files --config {{.CSPELL_CONFIG}} $STAGED_FILES || EXIT_CODE=$?
+            if [ "$EXIT_CODE" != '0' ]; then
+              .config/log warn 'Possible spelling errors were detected. Take appropriate action before merging changes.'
+            fi
           fi
         ignore_errors: true
 
@@ -315,7 +401,9 @@ tasks:
       **Example scanning specific file:**
       `task lint:toml -- myfile.toml`
     cmds:
-      - poetry run check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid TOML{{else}}the project'\''s TOML files are valid{{end}}'
+        {{.PYTHON_HANDLE}}check-toml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   vagrant:
     deps:
@@ -330,7 +418,9 @@ tasks:
 
       For more information on `vagrant validate`, see the [Vagrant website](https://www.vagrantup.com/docs/cli/validate).
     cmds:
-      - vagrant validate
+      - |
+        .config/log info 'Validating the Vagrantfile'
+        vagrant validate
 
   xml:
     deps:
@@ -348,7 +438,9 @@ tasks:
       **Example scanning specific file:**
       `task lint:xml -- myfile.xml`
     cmds:
-      - poetry run check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Ensuring {{if .CLI_ARGS}}{{.CLI_ARGS}} is valid XML{{else}}the project contains only valid XML{{end}}'
+        {{.PYTHON_HANDLE}}check-xml {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
 
   yaml:
     deps:
@@ -375,4 +467,6 @@ tasks:
 
       For more information, see the [YAML Lint GitHub page](https://github.com/adrienverge/yamllint).
     cmds:
-      - poetry run yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
+      - |
+        .config/log info 'Linting {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}the project{{end}} with `yamllint`'
+        {{.PYTHON_HANDLE}}yamllint -c {{.YAMLLINT_CONFIG}} -s {{if .CLI_ARGS}}{{.CLI_ARGS}}{{else}}.{{end}}
